# grafana/provisioning/datasources/prometheus.yml
# Sử dụng container names trong shared Docker network: fire-detection-network
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus.default.svc:9090
    isDefault: true
    editable: false

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    url: http://alertmanager.default.svc:9093
    jsonData:
      implementation: prometheus