apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-binhphuoc
  namespace: default
  labels:
    app: inference
    tier: edge
    location: binhphuoc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
        tier: edge
        location: binhphuoc
    spec:

      containers:
        - name: inference
          image: fire-inference-python:v2
          imagePullPolicy: Never
          env:
            - name: MQTT_BROKER
              value: mqtt-broker-binhphuoc.default.svc
            - name: MQTT_PORT
              value: "1883"
            - name: INTERVAL_SECONDS
              value: "30"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            limits:
              memory: 1024Mi
              cpu: "1000m"
            requests:
              memory: 512Mi
              cpu: "500m"
