apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-binhphuoc
  namespace: default
  labels:
    app: inference
    tier: edge
    location: binhphuoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
        tier: edge
        location: binhphuoc
    spec:

      containers:
        - name: inference
          image: fire-inference-python:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MQTT_BROKER
              value: mqtt-broker-binhphuoc.default.svc
            - name: MQTT_PORT
              value: "1883"
            - name: INTERVAL_SECONDS
              value: "30"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            limits:
              memory: 128Mi
              cpu: "250m"
            requests:
              memory: 64Mi
              cpu: "100m"
          volumeMounts:
            - name: model-vol
              mountPath: /model/fire_detection.onnx
              subPath: fire_detection.onnx
              readOnly: true
      volumes:
        - name: model-vol
          configMap:
            name: edge-model-config
