apiVersion: v1
kind: ConfigMap
metadata:
  name: frame-sources-dalat
  namespace: default
data:
  sources.json: |
    [
      {
        "id": "cam-dalat-01",
        "file": "dalat-nofire.mp4",
        "url": "https://storage.googleapis.com/edge-fire-cameras/dalat/dalat-nofire.mp4",
        "lat": 11.94,
        "lon": 108.44,
        "description": "Da Lat pine forest"
      }
    ]
