apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: fire-detection
  labels:
    app: mqtt-broker
    tier: edge
spec:
  selector:
    app: mqtt-broker
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
