apiVersion: v1
kind: ConfigMap
metadata:
  name: frame-sources-binhphuoc
  namespace: default
data:
  sources.json: |
    [
      {
        "id": "cam-binhphuoc-01",
        "file": "binhphuoc-fire.mp4",
        "url": "https://storage.googleapis.com/edge-fire-cameras/binhphuoc/binhphuoc-fire.mp4",
        "lat": 11.75,
        "lon": 106.90,
        "description": "Binh Phuoc forest area"
      }
    ]
